# Generated by Django 2.2.5 on 2019-09-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190907_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
