# Generated by Django 2.2.5 on 2019-09-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190910_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_year',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_year',
            field=models.IntegerField(max_length=7),
        ),
    ]
