# Generated by Django 2.2.5 on 2019-09-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190910_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='end_year',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='start_year',
            new_name='start_date',
        ),
    ]
